language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
  - openjdk6
  
branches:
  only:
  - master

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Cs1IyGaJQ6fV9WZGaBZy2Zus3pEpP6JUMl4AJG9b2MB6ESFA8vOuNUdHHcs+XDNs6uuseactkUSik9P8U653B3Kzna+NlrJcR+qYgPIM45o2oq3KQujPUW4M3XqMbIWAfjPWfW6DAErub1K5Aff0T5SnG4hGNdAqFnAn3qC/h84="
